// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
// </auto-generated>

namespace DFM_BPM.Admin
{
    public partial class EmailLog
    {
        protected global::System.Web.UI.WebControls.TextBox txtFilterPetId;
        protected global::System.Web.UI.WebControls.DropDownList ddlTopN;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.GridView gvLog;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litDLogID;
        protected global::System.Web.UI.WebControls.Literal litDDate;
        protected global::System.Web.UI.WebControls.Literal litDEvent;
        protected global::System.Web.UI.WebControls.Literal litDPetID;
        protected global::System.Web.UI.WebControls.Literal litDTo;
        protected global::System.Web.UI.WebControls.Literal litDCc;
        protected global::System.Web.UI.WebControls.Literal litDSubject;
        protected global::System.Web.UI.WebControls.Literal litDStatus;
        protected global::System.Web.UI.WebControls.Literal litDError;
        protected global::System.Web.UI.WebControls.Literal litDSentBy;
        protected global::System.Web.UI.WebControls.Literal litDBody;
    }
}
