// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
// </auto-generated>

namespace DFM_BPM.Admin
{
    public partial class EmailConfig
    {
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.GridView gvConfig;
        protected global::System.Web.UI.WebControls.Panel pnlEdit;
        protected global::System.Web.UI.WebControls.TextBox txtEditKey;
        protected global::System.Web.UI.WebControls.TextBox txtEditValue;
        protected global::System.Web.UI.WebControls.CheckBox chkEditEncrypt;
        protected global::System.Web.UI.WebControls.Button btnSaveConfig;
        protected global::System.Web.UI.WebControls.Button btnCancelEdit;
        protected global::System.Web.UI.WebControls.TextBox txtToolInput;
        protected global::System.Web.UI.WebControls.Button btnEncrypt;
        protected global::System.Web.UI.WebControls.Button btnDecrypt;
        protected global::System.Web.UI.WebControls.Panel pnlToolResult;
        protected global::System.Web.UI.WebControls.Literal litToolResult;
        protected global::System.Web.UI.WebControls.TextBox txtTestTo;
        protected global::System.Web.UI.WebControls.Button btnTestSmtp;
        protected global::System.Web.UI.WebControls.Panel pnlTestResult;
        protected global::System.Web.UI.WebControls.Literal litTestResult;
    }
}
