//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM_BPM.Admin {
    
    
    public partial class PortfolioHierarchy {
        
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.HiddenField hfAction;
        protected global::System.Web.UI.WebControls.HiddenField hfActionId;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedResourceId;
        protected global::System.Web.UI.WebControls.Button btnDoAction;
        protected global::System.Web.UI.WebControls.HiddenField hfEditResourceId;
        protected global::System.Web.UI.WebControls.TextBox txtResourceName;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlParent;
        protected global::System.Web.UI.WebControls.DropDownList ddlResourceActive;
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;
        protected global::System.Web.UI.WebControls.Panel pnlCurrentPhoto;
        protected global::System.Web.UI.WebControls.Image imgCurrentPhoto;
        protected global::System.Web.UI.WebControls.Button btnSaveResource;
        protected global::System.Web.UI.WebControls.Button btnCancelResource;
        protected global::System.Web.UI.WebControls.Literal litTree;
        protected global::System.Web.UI.WebControls.Panel pnlSelectedProjects;
        protected global::System.Web.UI.WebControls.Literal litSelectedResourceName;
        protected global::System.Web.UI.WebControls.GridView gvSelectedProjects;
    }
}
