//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM_BPM.Forms {
    
    
    public partial class ProjectRegistration {
        
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.HiddenField hfProjectId;
        protected global::System.Web.UI.WebControls.Button btnDeleteProject;
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteProject;
        protected global::System.Web.UI.WebControls.Literal litProjectPortfolioCount;
        protected global::System.Web.UI.WebControls.Button btnNewProject;
        protected global::System.Web.UI.WebControls.GridView gvProjectPortfolio;
        protected global::System.Web.UI.WebControls.Panel pnlCreatedInfo;
        protected global::System.Web.UI.WebControls.Literal litCreatedInfo;
        protected global::System.Web.UI.WebControls.RadioButtonList rblProjectMode;
        protected global::System.Web.UI.WebControls.PlaceHolder phJiraSelect;
        protected global::System.Web.UI.WebControls.DropDownList ddlProject;
        protected global::System.Web.UI.WebControls.PlaceHolder phNonJiraSelect;
        protected global::System.Web.UI.WebControls.TextBox txtNonJiraProjectId;
        protected global::System.Web.UI.WebControls.TextBox txtProjectName;
        protected global::System.Web.UI.WebControls.TextBox txtProjectManager;
        protected global::System.Web.UI.WebControls.DropDownList ddlActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Panel pnlProjectDetails;
        protected global::System.Web.UI.WebControls.Literal litJProjectType;
        protected global::System.Web.UI.WebControls.Literal litJStage;
        protected global::System.Web.UI.WebControls.Literal litJRag;
        protected global::System.Web.UI.WebControls.Literal litJDept;
        protected global::System.Web.UI.WebControls.Literal litJPlatform;
        protected global::System.Web.UI.WebControls.Literal litJTech;
        protected global::System.Web.UI.WebControls.Literal litJAccExec;
        protected global::System.Web.UI.WebControls.Literal litJAccExecLead;
        protected global::System.Web.UI.WebControls.Literal litJSmeLead;
        protected global::System.Web.UI.WebControls.Literal litJOverallStatus;
        protected global::System.Web.UI.WebControls.Panel pnlNoProject;
        protected global::System.Web.UI.WebControls.Literal litNoProjectMsg;
        protected global::System.Web.UI.WebControls.Panel pnlProjectPets;
        protected global::System.Web.UI.WebControls.GridView gvProjectPets;
        protected global::System.Web.UI.WebControls.Panel pnlSizing;
        protected global::System.Web.UI.WebControls.Literal litSizingBadge;
        protected global::System.Web.UI.WebControls.Literal litSizingSavedInfo;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ1;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ2;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ3;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ4;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ5;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ6;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ7;
        protected global::System.Web.UI.WebControls.Button btnSizingSave;
    }
}
