//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM_BPM.Forms {


    public partial class ProjectRegistration {

        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.HiddenField hfProjectId;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioProjectFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioTypeFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioAccountableExecLeadFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioSmeLeadFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioViewFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlPortfolioStatusFilter;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolioFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolioToDate;
        protected global::System.Web.UI.WebControls.Button btnPortfolioApply;
        protected global::System.Web.UI.WebControls.Button btnPortfolioReset;
        protected global::System.Web.UI.WebControls.Button btnPortfolioExport;
        protected global::System.Web.UI.WebControls.Literal litPortfolioProjectsCount;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolioProjectSearch;
        protected global::System.Web.UI.WebControls.Button btnPortfolioProjectSearch;
        protected global::System.Web.UI.WebControls.Button btnPortfolioProjectSearchReset;
        protected global::System.Web.UI.WebControls.Literal litPortfolioProjectTree;
        protected global::System.Web.UI.WebControls.LinkButton btnPortfolioPrevPage;
        protected global::System.Web.UI.WebControls.Literal litPortfolioPageInfo;
        protected global::System.Web.UI.WebControls.LinkButton btnPortfolioNextPage;
        protected global::System.Web.UI.WebControls.HiddenField hfPortfolioActionProjectId;
        protected global::System.Web.UI.WebControls.Button btnPortfolioShowSpendRequests;
        protected global::System.Web.UI.WebControls.Button btnPortfolioShowBudget;
        protected global::System.Web.UI.WebControls.Button btnPortfolioShowInvoices;
        protected global::System.Web.UI.WebControls.Literal litPortfolioSRModalProject;
        protected global::System.Web.UI.WebControls.GridView gvPortfolioModalSpendRequests;
        protected global::System.Web.UI.WebControls.GridView gvPortfolioModalLineItems;
        protected global::System.Web.UI.WebControls.Literal litPortfolioBgtModalProject;
        protected global::System.Web.UI.WebControls.GridView gvPortfolioModalBudgetLines;
        protected global::System.Web.UI.WebControls.Panel pnlPortfolioBudgetInvoiceDetail;
        protected global::System.Web.UI.WebControls.Literal litPortfolioBgtInvLineId;
        protected global::System.Web.UI.WebControls.GridView gvPortfolioModalBudgetInvoices;
        protected global::System.Web.UI.WebControls.Literal litPortfolioInvModalProject;
        protected global::System.Web.UI.WebControls.GridView gvPortfolioModalInvoices;
        protected global::System.Web.UI.WebControls.HiddenField hfPortfolioDeletePetId;
        protected global::System.Web.UI.WebControls.Button btnPortfolioConfirmDeletePet;
        protected global::System.Web.UI.WebControls.Button btnDeleteProject;
        protected global::System.Web.UI.WebControls.Button btnConfirmDeleteProject;
        protected global::System.Web.UI.WebControls.Panel pnlCreatedInfo;
        protected global::System.Web.UI.WebControls.Literal litCreatedInfo;
        protected global::System.Web.UI.WebControls.RadioButtonList rblProjectMode;
        protected global::System.Web.UI.WebControls.PlaceHolder phJiraSelect;
        protected global::System.Web.UI.WebControls.DropDownList ddlProject;
        protected global::System.Web.UI.WebControls.PlaceHolder phNonJiraSelect;
        protected global::System.Web.UI.WebControls.TextBox txtNonJiraProjectId;
        protected global::System.Web.UI.WebControls.TextBox txtProjectName;
        protected global::System.Web.UI.WebControls.TextBox txtProjectManager;
        protected global::System.Web.UI.WebControls.DropDownList ddlHierExec;
        protected global::System.Web.UI.WebControls.DropDownList ddlHierExecLead;
        protected global::System.Web.UI.WebControls.DropDownList ddlHierSmeLead;
        protected global::System.Web.UI.WebControls.ListBox ddlHierEngineer;
        protected global::System.Web.UI.WebControls.DropDownList ddlActive;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Panel pnlProjectDetails;
        protected global::System.Web.UI.WebControls.Literal litJProjectType;
        protected global::System.Web.UI.WebControls.Literal litJStage;
        protected global::System.Web.UI.WebControls.Literal litJRag;
        protected global::System.Web.UI.WebControls.Literal litJDept;
        protected global::System.Web.UI.WebControls.Literal litJPlatform;
        protected global::System.Web.UI.WebControls.Literal litJTech;
        protected global::System.Web.UI.WebControls.Literal litJAccExec;
        protected global::System.Web.UI.WebControls.Literal litJAccExecLead;
        protected global::System.Web.UI.WebControls.Literal litJSmeLead;
        protected global::System.Web.UI.WebControls.Literal litJOverallStatus;
        protected global::System.Web.UI.WebControls.Panel pnlNoProject;
        protected global::System.Web.UI.WebControls.Literal litNoProjectMsg;
        protected global::System.Web.UI.WebControls.Panel pnlProjectPets;
        protected global::System.Web.UI.WebControls.GridView gvProjectPets;
        protected global::System.Web.UI.WebControls.Panel pnlSizing;
        protected global::System.Web.UI.WebControls.Literal litSizingBadge;
        protected global::System.Web.UI.WebControls.Literal litSizingSavedInfo;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ1;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ2;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ3;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ4;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ5;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ6;
        protected global::System.Web.UI.WebControls.HiddenField hfSzQ7;
        protected global::System.Web.UI.WebControls.Button btnSizingSave;
    }
}
