//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM_BPM {
    
    
    public partial class DefaultPage {
        
        /// <summary>
        /// smDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager smDashboard;
        
        /// <summary>
        /// litLastSync control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litLastSync;
        
        /// <summary>
        /// ddlProject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlProject;
        
        /// <summary>
        /// ddlType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        
        /// <summary>
        /// ddlView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlView;
        
        /// <summary>
        /// ddlStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        
        /// <summary>
        /// txtFromDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        
        /// <summary>
        /// txtToDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        
        /// <summary>
        /// btnApply control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnApply;
        
        /// <summary>
        /// btnReset control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnReset;
        
        /// <summary>
        /// litProjects control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litProjects;
        
        /// <summary>
        /// litPET control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPET;
        
        /// <summary>
        /// litPending control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPending;
        
        /// <summary>
        /// litApproved control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litApproved;
        
        /// <summary>
        /// litRejected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRejected;
        
        /// <summary>
        /// litCapexBudget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCapexBudget;
        
        /// <summary>
        /// litOpexBudget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litOpexBudget;
        
        /// <summary>
        /// litRegisteredProjectsCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRegisteredProjectsCount;
        
        /// <summary>
        /// litRegisteredProjectRows control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litRegisteredProjectRows;
        
        /// <summary>
        /// btnPrevPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnPrevPage;
        
        /// <summary>
        /// litPageInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPageInfo;
        
        /// <summary>
        /// btnNextPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnNextPage;

        protected global::System.Web.UI.WebControls.Literal litBulkApprovalCount;

        protected global::System.Web.UI.WebControls.GridView gvBulkApproval;

        protected global::System.Web.UI.WebControls.TextBox txtBulkApprovalComments;

        protected global::System.Web.UI.WebControls.Button btnBulkApproveSelected;

        protected global::System.Web.UI.WebControls.Button btnBulkSendBackSelected;

        protected global::System.Web.UI.WebControls.Label lblBulkApprovalMsg;

        protected global::System.Web.UI.WebControls.GridView gvProjectWiseKpi;
        
        /// <summary>
        /// hfDeletePetId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfDeletePetId;
        
        /// <summary>
        /// btnConfirmDeletePet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmDeletePet;

        /// <summary>
        /// updDashboardActions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updDashboardActions;

        protected global::System.Web.UI.WebControls.HiddenField hfActionProjectId;
        protected global::System.Web.UI.WebControls.Button btnShowProjectTracker;
        protected global::System.Web.UI.WebControls.Button btnShowSpendRequests;
        protected global::System.Web.UI.WebControls.Button btnShowBudget;
        protected global::System.Web.UI.WebControls.Button btnShowInvoices;
        protected global::System.Web.UI.WebControls.Literal litSRModalProject;
        protected global::System.Web.UI.WebControls.GridView gvModalSpendRequests;
        protected global::System.Web.UI.WebControls.GridView gvModalLineItems;
        protected global::System.Web.UI.WebControls.Literal litTrackerModalProject;
        protected global::System.Web.UI.WebControls.Literal litTrackerProjectTitle;
        protected global::System.Web.UI.WebControls.Literal litTrackerProjectName;
        protected global::System.Web.UI.WebControls.Literal litTrackerDemandId;
        protected global::System.Web.UI.WebControls.Literal litTrackerApprovedBudget;
        protected global::System.Web.UI.WebControls.Literal litTrackerCapexId;
        protected global::System.Web.UI.WebControls.Literal litTrackerApprovedBudgetTile;
        protected global::System.Web.UI.WebControls.Literal litTrackerCommitted;
        protected global::System.Web.UI.WebControls.Literal litTrackerInvoiced;
        protected global::System.Web.UI.WebControls.Literal litTrackerRemaining;
        protected global::System.Web.UI.WebControls.Literal litTrackerUtilization;
        protected global::System.Web.UI.WebControls.Literal litTrackerLpoIssued;
        protected global::System.Web.UI.WebControls.Literal litTrackerPendingCamLpo;
        protected global::System.Web.UI.WebControls.Literal litTrackerPaidInvoices;
        protected global::System.Web.UI.WebControls.GridView gvProjectBudgetTracker;
        protected global::System.Web.UI.WebControls.Literal litBgtModalProject;
        protected global::System.Web.UI.WebControls.GridView gvModalBudgetLines;
        protected global::System.Web.UI.WebControls.Panel pnlBudgetInvoiceDetail;
        protected global::System.Web.UI.WebControls.Literal litBgtInvLineId;
        protected global::System.Web.UI.WebControls.GridView gvModalBudgetInvoices;
        protected global::System.Web.UI.WebControls.Literal litInvModalProject;
        protected global::System.Web.UI.WebControls.GridView gvModalInvoices;
    }
}
