//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFM_BPM {


    public partial class DefaultPage {

        protected global::System.Web.UI.WebControls.Literal litLastSync;
        protected global::System.Web.UI.WebControls.Button btnExportDashboard;
        protected global::System.Web.UI.WebControls.Literal litProjects;
        protected global::System.Web.UI.WebControls.Literal litPET;
        protected global::System.Web.UI.WebControls.Literal litPending;
        protected global::System.Web.UI.WebControls.Literal litApproved;
        protected global::System.Web.UI.WebControls.Literal litRejected;
        protected global::System.Web.UI.WebControls.Literal litCapexBudget;
        protected global::System.Web.UI.WebControls.Literal litOpexBudget;
        protected global::System.Web.UI.WebControls.Literal litInvoiceCount;
        protected global::System.Web.UI.WebControls.Literal litInvoiceAmount;
        protected global::System.Web.UI.WebControls.Literal litMyBudgetLines;
        protected global::System.Web.UI.WebControls.Literal litActiveProjects;
        protected global::System.Web.UI.WebControls.Literal litCapexOpexChart;
        protected global::System.Web.UI.WebControls.Literal litBudgetChart;
        protected global::System.Web.UI.WebControls.Literal litMonthlySpendChart;
        protected global::System.Web.UI.WebControls.Literal litInvoiceTrendChart;
        protected global::System.Web.UI.WebControls.GridView gvRecentProjects;
        protected global::System.Web.UI.WebControls.Literal litPendingApprovals;
        protected global::System.Web.UI.WebControls.GridView gvRecentRequests;
        protected global::System.Web.UI.WebControls.GridView gvRecentInvoices;
    }
}
